/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#fcf8ff",
        "surface-dim": "#dcd9df",
        "surface-bright": "#fcf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f2f9",
        "surface-container": "#f0ecf3",
        "surface-container-high": "#eae7ed",
        "surface-container-highest": "#e4e1e8",
        "on-surface": "#1b1b20",
        "on-surface-variant": "#464650",
        "inverse-surface": "#303035",
        "inverse-on-surface": "#f3eff6",
        outline: "#777681",
        "outline-variant": "#c7c5d2",
        "surface-tint": "#55589b",
        primary: "#141558",
        "on-primary": "#ffffff",
        "primary-container": "#2b2d6e",
        "on-primary-container": "#9597df",
        "inverse-primary": "#c0c1ff",
        secondary: "#006b58",
        "on-secondary": "#ffffff",
        "secondary-container": "#6df6d4",
        "on-secondary-container": "#00705c",
        tertiary: "#301c00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#4c2f00",
        "on-tertiary-container": "#d59024",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#e1e0ff",
        "primary-fixed-dim": "#c0c1ff",
        "on-primary-fixed": "#101054",
        "on-primary-fixed-variant": "#3d4081",
        "secondary-fixed": "#70f9d7",
        "secondary-fixed-dim": "#4fdcbc",
        "on-secondary-fixed": "#002019",
        "on-secondary-fixed-variant": "#005142",
        "tertiary-fixed": "#ffddb5",
        "tertiary-fixed-dim": "#ffb958",
        "on-tertiary-fixed": "#2a1800",
        "on-tertiary-fixed-variant": "#643f00",
        background: "#fcf8ff",
        "on-background": "#1b1b20",
        "surface-variant": "#e4e1e8",
        // Semantic extras used in results pages
        warning: "#FF9800",
        "warning-container": "#FFF3E0",
        "on-warning-container": "#E65100",
        info: "#2196F3",
        "info-container": "#E3F2FD",
        "on-info-container": "#0D47A1",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        "container-padding-mobile": "20px",
        "container-padding-desktop": "40px",
        gutter: "24px",
        "section-gap": "64px",
      },
      fontFamily: {
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
      },
      boxShadow: {
        "level-1": "0 4px 20px rgba(20, 21, 88, 0.04)",
        "level-2": "0 12px 40px rgba(20, 21, 88, 0.08)",
      },
    },
  },
  plugins: [],
}
