import { Link } from 'react-router-dom'
import { useScan } from '../context/useScan'

const destinationLabels = { school: 'School', public: 'Public', social_media: 'Social Media', 'social-media': 'Social Media', ai: 'AI', private_chat: 'Private Chat', 'private-chat': 'Private Chat' }

export default function ProfilePage() {
  const { user, checkHistory, practiceStats } = useScan()
  const insights = checkHistory.reduce((total, check) => total + check.flags.length, 0) + practiceStats.correct
  return (
    <div className="flex flex-col gap-12">
      <header className="flex flex-col md:flex-row items-start md:items-center gap-6"><div className="w-20 h-20 md:w-24 md:h-24 rounded-full shadow-lg bg-surface-container-highest shrink-0 flex items-center justify-center"><span className="material-symbols-outlined text-[48px] text-on-surface-variant">account_circle</span></div><div className="flex-1"><h1 className="font-headline-lg text-headline-lg md:font-display-lg md:text-display-lg text-on-surface mb-2">{user.name}</h1><div className="flex items-center gap-2 text-on-surface-variant"><span className="material-symbols-outlined text-secondary filled-icon">verified_user</span><span className="font-body-md text-body-md">Personal profile</span></div></div></header>
      <section><h2 className="font-headline-md text-headline-md text-on-surface mb-6">Journey Overview</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-6"><div className="bg-surface-container-lowest rounded-xl p-6 shadow-level-1"><span className="font-body-lg text-body-lg text-on-surface-variant">Checks completed</span><p className="font-display-lg text-display-lg text-on-surface mt-4">{checkHistory.length}</p></div><div className="bg-surface-container-lowest rounded-xl p-6 shadow-level-1"><span className="font-body-lg text-body-lg text-on-surface-variant">Insights gained</span><p className="font-display-lg text-display-lg text-on-surface mt-4">{insights}</p></div></div></section>
      <section><div className="flex items-center justify-between mb-6"><h2 className="font-headline-md text-headline-md text-on-surface">Responsibility History</h2><Link to="/check" className="text-secondary font-label-md">New check</Link></div>{checkHistory.length === 0 ? <div className="bg-surface-container-low rounded-xl p-8 text-center"><p className="font-body-md text-body-md text-on-surface-variant">Your history will grow as you make checks.</p></div> : <div className="flex flex-col gap-4">{checkHistory.map(item => <Link to="/profile/detail" key={item.id} className="bg-surface-container-lowest rounded-xl p-4 flex items-center gap-4 shadow-level-1 hover:bg-surface-container-low transition-colors"><div className="w-14 h-14 rounded-lg bg-surface-container-highest flex items-center justify-center shrink-0"><span className="material-symbols-outlined text-on-surface-variant">description</span></div><div className="flex-1 min-w-0"><h3 className="font-headline-md text-lg text-on-surface truncate">{item.title}</h3><p className="font-body-md text-body-md text-on-surface-variant">{destinationLabels[item.destination] || 'Content check'} · {item.flags.length ? `${item.flags.length} signal${item.flags.length === 1 ? '' : 's'}` : 'No signals'}</p></div><span className="material-symbols-outlined text-on-surface-variant">arrow_forward</span></Link>)}</div>}</section>
    </div>
  )
}
